import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { LocalRecordsStore } from "../src/storage/local-records.js";
import { getRecordConnections, linkPath, markdownLinks, recordId } from "../src/storage/record-graph.js";
import type { StoredRecord } from "../src/storage/records-store.js";

const files: string[] = [];
afterEach(async () => {
  await Promise.all(files.splice(0).map((root) => fs.rm(root, { recursive: true, force: true })));
});

function entry(pathname: string, content: string): StoredRecord {
  return { path: pathname, date: "2026-09-16", type: pathname.startsWith("journals/") ? "journal" : "note", content };
}

const a = "notes/2026/202609/20260916-努力.md";
const b = "notes/2026/202609/20260916-行动.md";
const c = "journals/2026/202609/20260916-记录.md";

it("recognizes standard and reference links, Unicode URLs, backlinks, and legacy files without IDs", () => {
  const records = [
    entry(a, `---\nid: cr_12345678\ntitle: "努力与选择"\n---\n\n参考 [行动](20260916-%E8%A1%8C%E5%8A%A8.md) 和 [当天][day].\n\n[day]: ../../../journals/2026/202609/20260916-%E8%AE%B0%E5%BD%95.md\n`),
    entry(b, `# 把自己交出去\n\n反过来链接 [选择](20260916-%E5%8A%AA%E5%8A%9B.md).\n`),
    entry(c, "# 今天\n\n内容。"),
  ];
  const graph = getRecordConnections(records, { id: "cr_12345678" });
  expect(graph.record).toMatchObject({ path: a, title: "努力与选择", id: "cr_12345678" });
  expect(graph.outgoing.map(({ path, id }) => [path, id])).toEqual([[c, undefined], [b, undefined]].sort((x, y) => x[0]!.localeCompare(y[0]!)));
  expect(graph.backlinks).toMatchObject([{ path: b, title: "把自己交出去" }]);
  expect(getRecordConnections(records, { path: c }).backlinks.map(({ path }) => path)).toEqual([a]);
});

it("never treats images, external destinations, code, anchor-only links, or escaping paths as graph edges", () => {
  const markdown = [
    "[yes](20260916-行动.md)",
    "![screenshot](20260916-行动.md)",
    "[website](https://example.com/20260916-行动.md)",
    "[outside](../../../../private.md)",
    "[anchor](#topic)",
    "`[code](20260916-行动.md)`",
    "```md", "[fenced](20260916-行动.md)", "```",
  ].join("\n");
  const graph = getRecordConnections([entry(a, markdown), entry(b, "# B")], { path: a });
  expect(graph.outgoing).toHaveLength(1);
  expect(graph.outgoing[0]?.path).toBe(b);
  expect(graph.unresolved).toEqual([]);
  expect(linkPath(a, "../../../../private.md")).toBeUndefined();
  expect(linkPath(a, "%ZZ.md")).toBeUndefined();
  expect(markdownLinks(markdown).some(({ label }) => label === "fenced")).toBe(false);
});

it("reports dangling links without fabricating targets", () => {
  const graph = getRecordConnections([entry(a, "[missing](missing.md)\n")], { path: a });
  expect(graph.outgoing).toEqual([]);
  expect(graph.unresolved).toEqual([{ label: "missing", target: "missing.md" }]);
});

it("does not confuse a file rename with identity and rejects duplicate IDs", () => {
  const records = [entry(a, "---\nid: cr_12345678\n---\n# A"), entry(b, "# B")];
  expect(getRecordConnections(records, { id: "cr_12345678" }).record.path).toBe(a);
  const moved = { ...records[0]!, path: "notes/2026/202609/renamed.md" };
  expect(getRecordConnections([moved, records[1]!], { id: "cr_12345678" }).record.path).toBe(moved.path);
  expect(() => getRecordConnections([moved, entry(c, moved.content)], { id: "cr_12345678" })).toThrow(/Duplicate record ID/);
  expect(() => getRecordConnections(records, {})).toThrow(/exactly one/);
});

describe("IDs generated by Capture & Reflect", () => {
  it("assigns distinct IDs to new notes, journals, and reviews; legacy Markdown remains valid", async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), "portable-graph-"));
    files.push(root);
    const store = new LocalRecordsStore(root);
    const note = await store.captureNote({ date: "2026-09-16", title: "行动", keyword: "行动", content: "# Original note\n用户的文字。" });
    const journal = await store.captureJournal({ date: "2026-09-16", title: "记录", keyword: "记录", content: "今天有个想法。" });
    const review = await store.saveReview({ date: "2026-09-17", from: "2026-09-16", to: "2026-09-16", title: "复盘", keyword: "复盘", content: "从行动中学习。", sourcePaths: [note.path] });
    const ids = await Promise.all([note.path, journal.path, review.path].map(async (record) => recordId(await fs.readFile(path.join(root, record), "utf8"))));
    expect(ids.every((id) => /^cr_[0-9a-f-]{36}$/.test(id ?? ""))).toBe(true);
    expect(new Set(ids).size).toBe(3);
    const markdown = await fs.readFile(path.join(root, note.path), "utf8");
    expect(markdown).toContain("# Original note\n用户的文字。");
    expect(recordId("# Old Markdown\nStill readable.")).toBeUndefined();
  });
});
